In [32]:
import numpy as np
import matplotlib.pyplot as plt

In [33]:
#根据题意输入数据
X = np.array([[1,3,3],
              [1,4,3],
              [1,1,1],
              [1,0,2]])
#标签
Y = np.array([[1],
              [1],
              [-1],
              [-1]])

#权值初始化，3行1列，取值范围（-1,1）
#[3,1]位随机数生成的形状，-0.5表示范围在（-0.5到0.5）之间
#（-0.5到0.5）*2表示范围在（-1,1）之间
W = (np.random.random([3,1])-0.5)*2
print(W)
     
#设置学习率
lr = 0.11

#神经网络输出,初始值设为0
O = 0

#权值更新的函数：
#4行3列的X矩阵和3行1列的W矩阵相乘得到4行1列的矩阵
#4行3列转置成3行4列的X矩阵和4行1列（Y-0）矩阵相乘得到3行1列的矩阵
#X.shape[0]，由于X是4行3列的矩阵，shape.[0]相当于得到了行数
#/int（X.shape[0]）相当于对于（X.T.dot(Y-0)）进行一个平均
def update():
    global X,Y,W,lr
    O = np.sign(np.dot(X,W)) # shape:(3,1)
    W_C = lr*(X.T.dot(Y-O))/int(X.shape[0])
    W = W + W_C

[[-0.41541488]
 [-0.14766616]
 [-0.25244648]]


In [34]:
for i in range(100):
    update()#更新权值
    print(W)#打印当前权值
    print(i)#打印迭代次数
    O = np.sign(np.dot(X,W))#计算当前输出  
    if(O == Y).all(): #如果实际输出等于期望输出，模型收敛，循环结束
        print('Finished')
        print('epoch:',i)
        break

#正样本
x1 = [3,4]
y1 = [3,3]
#负样本
x2 = [1,0]
y2 = [1,2]

#计算分界线的斜率以及截距
k = -W[1]/W[2]
d = -W[0]/W[2]
print('k=',k)
print('d=',d)

xdata = (0,5)

plt.figure()
plt.plot(xdata,xdata*k+d,'r')
plt.scatter(x1,y1,c='b')
plt.scatter(x2,y2,c='y')
plt.show()

[[-0.30541488]
 [ 0.23733384]
 [ 0.07755352]]
0
[[-0.36041488]
 [ 0.18233384]
 [ 0.02255352]]
1
Finished
epoch: 1
k= [-8.08449514]
d= [15.98042513]
