AI MOOC： **www.ai-xlab.com**  

In [1]:
import numpy as np

In [6]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(array.ndim)#维度

2


In [9]:
print(array.shape)#形状

(3, 3)


In [10]:
print(array.size)#大小

9


In [11]:
print(array.dtype)#元素类型

int32
