AI MOOC： **www.ai-xlab.com**  

In [1]:
import numpy as np

In [2]:
sample1 = np.random.random((3,2))#生成3行2列从0到1的随机数
print(sample1)

[[ 0.42548654  0.60831272]
 [ 0.48034909  0.70289579]
 [ 0.96871932  0.33469266]]


In [3]:
sample2 = np.random.normal(size=(3,2))#生成3行2列符合标准正态分布的随机数
print(sample2)

[[ 0.82645622 -0.63300866]
 [ 0.18604463 -0.30988056]
 [-1.50301955 -0.51466896]]


In [4]:
sample3 = np.random.randint(0,10,size=(3,2))#生成3行2列从0到10的随机整数
print(sample3)

[[2 4]
 [3 1]
 [0 3]]


In [5]:
np.sum(sample1)#求和

3.5204561139867017

In [6]:
np.min(sample1)#求最小值

0.33469265548836047

In [7]:
np.max(sample1)#求最大值

0.96871931960307933

In [8]:
np.sum(sample1,axis=0)#对列求和

array([ 1.87455495,  1.64590117])

In [9]:
np.sum(sample1,axis=1)#对行求和

array([ 1.03379926,  1.18324488,  1.30341198])

In [10]:
print(sample1)

[[ 0.42548654  0.60831272]
 [ 0.48034909  0.70289579]
 [ 0.96871932  0.33469266]]


In [11]:
np.argmin(sample1)#求最小值的索引

5

In [12]:
np.argmax(sample1)#求最大值的索引

4

In [14]:
print(np.mean(sample1))#求平均值
print(sample1.mean())#求平均值

0.586742685664
0.586742685664


In [15]:
np.median(sample1)#求中位数

0.5443309058371042

In [16]:
np.sqrt(sample1)#开方

array([[ 0.65229329,  0.77994405],
       [ 0.69307221,  0.8383888 ],
       [ 0.9842354 ,  0.57852628]])

In [18]:
sample4 = np.random.randint(0,10,size=(1,10))
print(sample4)

[[9 2 3 0 2 8 1 3 2 8]]


In [19]:
np.sort(sample4)#排序

array([[0, 1, 2, 2, 2, 3, 3, 8, 8, 9]])

In [20]:
np.sort(sample1)

array([[ 0.42548654,  0.60831272],
       [ 0.48034909,  0.70289579],
       [ 0.33469266,  0.96871932]])

In [22]:
np.clip(sample4,2,7)#小于2就变成2，大于7就变为7

array([[7, 2, 3, 2, 2, 7, 2, 3, 2, 7]])